export const response = {
  "algorithms": [
    {
      "name": "rabin_karp",
      "time": 0.03328162500019971
    },
    {
      "name": "kmp",
      "time": 0.011061957999572769
    },
    {
      "name": "naive",
      "time": 0.009724083000037353
    },
    {
      "name": "suffix_tree",
      "time": 0.4583391250002933
    }
  ],
  "all_counter": {
    "11": 2,
    "20": 1,
    "28": 1,
    "50": 1,
    "61": 1,
    "94": 1,
    "2017": 1,
    "2018": 1,
    "2019": 3,
    "2020": 3,
    "2021": 9,
    "2022": 3,
    "2023": 2,
    "2nd": 1,
    "aakarshan": 1,
    "accessibility": 2,
    "account": 1,
    "admin": 2,
    "ai": 1,
    "algorithm": 1,
    "already": 1,
    "also": 1,
    "analytical": 1,
    "angular": 10,
    "angular2": 1,
    "anytime": 1,
    "api": 5,
    "apis": 1,
    "app": 5,
    "application": 6,
    "applications": 3,
    "appripriate": 1,
    "apr": 1,
    "april": 1,
    "architected": 3,
    "architecture": 3,
    "arduino": 1,
    "army": 1,
    "artboard": 1,
    "article": 1,
    "arts": 1,
    "audio": 1,
    "aug": 2,
    "august": 2,
    "authentication": 1,
    "authority": 1,
    "automatically": 1,
    "automation": 1,
    "aws": 2,
    "back": 2,
    "bangalore": 1,
    "bank": 1,
    "based": 2,
    "bases": 1,
    "batch": 2,
    "better": 1,
    "big": 2,
    "bigdata": 1,
    "bitbucket": 1,
    "blazing": 1,
    "block": 1,
    "blockchain": 2,
    "blockvote": 1,
    "boot": 5,
    "bootstrap": 2,
    "bot": 1,
    "buckle": 1,
    "build": 1,
    "building": 1,
    "built": 3,
    "business": 2,
    "caching": 1,
    "california": 2,
    "calls": 1,
    "capability": 1,
    "cassandra": 2,
    "cd": 1,
    "cgpa": 2,
    "chain": 1,
    "chatbot": 1,
    "china": 1,
    "chrome": 2,
    "ci": 1,
    "citizens": 1,
    "classics": 1,
    "clean": 1,
    "cleanup": 1,
    "click": 1,
    "client": 3,
    "cloud": 1,
    "code": 2,
    "coding": 2,
    "collaborate": 1,
    "collaborated": 1,
    "collaboration": 1,
    "colors": 1,
    "com": 1,
    "comakeit": 1,
    "combined": 1,
    "comments": 1,
    "communicating": 1,
    "company": 2,
    "competition": 1,
    "compliance": 1,
    "compose": 2,
    "compressing": 1,
    "computer": 3,
    "conducting": 1,
    "conference": 2,
    "consume": 1,
    "cool": 1,
    "coordinated": 1,
    "covered": 1,
    "crash": 1,
    "created": 1,
    "cross": 2,
    "css": 1,
    "currency": 1,
    "customizable": 1,
    "dashboard": 3,
    "data": 11,
    "database": 3,
    "dbs": 1,
    "deadlines": 1,
    "dec": 1,
    "demonstrate": 2,
    "deployed": 2,
    "deployment": 2,
    "design": 7,
    "designed": 4,
    "designing": 1,
    "develop": 2,
    "developed": 6,
    "development": 6,
    "device": 1,
    "devices": 1,
    "devops": 1,
    "divided": 2,
    "docker": 4,
    "document": 1,
    "download": 1,
    "drop": 1,
    "dynamic": 3,
    "education": 1,
    "educational": 1,
    "efficiency": 1,
    "efficiently": 1,
    "email": 1,
    "emotion": 1,
    "enables": 1,
    "end": 4,
    "engineer": 2,
    "engineering": 1,
    "engineers": 1,
    "error": 1,
    "errors": 1,
    "essay": 1,
    "every": 1,
    "experience": 1,
    "extension": 2,
    "extensively": 1,
    "failures": 1,
    "fair": 1,
    "fast": 1,
    "features": 3,
    "feb": 1,
    "fellow": 1,
    "fetch": 1,
    "file": 1,
    "firebase": 4,
    "firestore": 1,
    "first": 2,
    "form": 1,
    "framework": 1,
    "free": 1,
    "front": 2,
    "full": 3,
    "fullerton": 2,
    "fully": 1,
    "functional": 2,
    "functionalities": 2,
    "game": 1,
    "ganache": 1,
    "gatsby": 1,
    "get": 3,
    "gmail": 1,
    "google": 4,
    "got": 3,
    "hardware": 1,
    "havmor": 1,
    "health": 1,
    "help": 1,
    "heroku": 1,
    "hey": 1,
    "hibernate": 1,
    "highlighting": 1,
    "holistic": 1,
    "hong": 1,
    "http": 1,
    "hyderabad": 3,
    "images": 1,
    "implement": 1,
    "implemented": 6,
    "implementing": 2,
    "important": 1,
    "improved": 3,
    "increase": 2,
    "india": 4,
    "info": 1,
    "inspiration": 1,
    "institute": 1,
    "intern": 2,
    "ionic": 1,
    "iot": 5,
    "item": 1,
    "jan": 1,
    "java": 3,
    "javascript": 1,
    "jenkins": 1,
    "jet": 1,
    "joke": 1,
    "js": 1,
    "july": 1,
    "jun": 1,
    "june": 1,
    "kafka": 2,
    "keshav": 4,
    "keshavlingala": 1,
    "kids": 1,
    "knife": 1,
    "knowledge": 1,
    "kong": 1,
    "kubernetes": 1,
    "languages": 1,
    "last": 1,
    "learning": 1,
    "led": 1,
    "legacy": 1,
    "libraries": 1,
    "library": 4,
    "life": 1,
    "like": 3,
    "likes": 1,
    "lines": 1,
    "lingala": 2,
    "link": 1,
    "list": 1,
    "log": 1,
    "machine": 1,
    "maintain": 2,
    "maintained": 1,
    "manage": 1,
    "management": 1,
    "managing": 1,
    "manipulation": 1,
    "mar": 1,
    "mariadb": 1,
    "master": 2,
    "material": 2,
    "may": 4,
    "media": 1,
    "memorial": 1,
    "message": 2,
    "microservices": 1,
    "migration": 1,
    "minimax": 1,
    "mode": 2,
    "monolithic": 1,
    "movie": 1,
    "movies": 3,
    "mp3": 1,
    "multi": 1,
    "multiple": 2,
    "mvc": 2,
    "mysql": 1,
    "name": 1,
    "new": 3,
    "nlp": 3,
    "node": 1,
    "nodejs": 1,
    "nov": 1,
    "officer": 1,
    "offline": 1,
    "omdb": 1,
    "one": 1,
    "open": 1,
    "opening": 1,
    "optimization": 1,
    "orm": 1,
    "overview": 1,
    "part": 4,
    "parts": 2,
    "payment": 2,
    "performance": 2,
    "pi": 1,
    "pipelines": 1,
    "place": 1,
    "platform": 4,
    "poc": 1,
    "popcorn": 2,
    "portfolio": 1,
    "pothole": 2,
    "potholes": 1,
    "present": 2,
    "probably": 1,
    "problem": 2,
    "process": 6,
    "processes": 1,
    "processing": 1,
    "productivity": 2,
    "progressive": 1,
    "project": 6,
    "projects": 5,
    "prototype": 1,
    "purpose": 2,
    "python": 1,
    "quiz": 1,
    "random": 1,
    "raspberry": 1,
    "rds": 1,
    "reach": 1,
    "reaction": 1,
    "real": 6,
    "reduction": 2,
    "reliability": 1,
    "replies": 1,
    "report": 1,
    "reporting": 1,
    "rest": 2,
    "restful": 1,
    "resulted": 1,
    "resulting": 4,
    "retrieval": 1,
    "reusable": 1,
    "ride": 1,
    "room": 2,
    "runtime": 1,
    "scalability": 1,
    "schedules": 1,
    "scholar": 1,
    "science": 4,
    "script": 1,
    "scripting": 1,
    "second": 2,
    "senior": 1,
    "sep": 1,
    "sepolia": 1,
    "server": 3,
    "service": 1,
    "several": 1,
    "sharing": 1,
    "side": 3,
    "significant": 1,
    "simple": 3,
    "singapore": 1,
    "single": 1,
    "skills": 2,
    "smart": 2,
    "social": 1,
    "software": 4,
    "solidity": 1,
    "solving": 1,
    "soon": 1,
    "source": 1,
    "spark": 2,
    "splitwise": 3,
    "spring": 6,
    "squeezing": 1,
    "stack": 3,
    "standardized": 1,
    "standards": 1,
    "state": 1,
    "status": 1,
    "stories": 1,
    "student": 1,
    "students": 4,
    "submit": 1,
    "submitted": 1,
    "successfully": 1,
    "summarize": 1,
    "swift": 1,
    "swiss": 1,
    "synopsis": 1,
    "system": 3,
    "tastic": 1,
    "team": 1,
    "teams": 2,
    "tech": 1,
    "technologies": 9,
    "technology": 1,
    "telegram": 2,
    "testing": 1,
    "text": 1,
    "think": 1,
    "time": 7,
    "timeline": 2,
    "times": 2,
    "torrent": 1,
    "touch": 1,
    "truffle": 1,
    "two": 2,
    "understand": 1,
    "unit": 1,
    "university": 1,
    "updated": 2,
    "updates": 1,
    "use": 2,
    "used": 1,
    "user": 3,
    "users": 1,
    "using": 12,
    "view": 1,
    "virtusa": 1,
    "voting": 2,
    "way": 1,
    "wcag": 1,
    "weather": 1,
    "web": 4,
    "web3": 1,
    "webhook": 1,
    "webpage": 1,
    "work": 1,
    "worked": 2,
    "yify": 1,
    "youtube": 1,
    "zonal": 1
  },
  "recommended_top_keys": [
    {
      "avg_monthly_searches": 1300,
      "competition": "LOW",
      "text": "using"
    },
    {
      "avg_monthly_searches": 5400,
      "competition": "LOW",
      "text": "data"
    },
    {
      "avg_monthly_searches": 1900,
      "competition": "LOW",
      "text": "angular"
    },
    {
      "avg_monthly_searches": 390,
      "competition": "LOW",
      "text": "technologies"
    },
    {
      "avg_monthly_searches": 12100,
      "competition": "LOW",
      "text": "2021"
    },
    {
      "avg_monthly_searches": 9900,
      "competition": "LOW",
      "text": "design"
    },
    {
      "avg_monthly_searches": 49500,
      "competition": "LOW",
      "text": "time"
    },
    {
      "avg_monthly_searches": 3600,
      "competition": "LOW",
      "text": "development"
    },
    {
      "avg_monthly_searches": 5400,
      "competition": "LOW",
      "text": "application"
    },
    {
      "avg_monthly_searches": 8100,
      "competition": "LOW",
      "text": "real"
    },
    {
      "avg_monthly_searches": 6600,
      "competition": "LOW",
      "text": "project"
    },
    {
      "avg_monthly_searches": 5400,
      "competition": "LOW",
      "text": "process"
    },
    {
      "avg_monthly_searches": 5400,
      "competition": "LOW",
      "text": "implemented"
    },
    {
      "avg_monthly_searches": 12100,
      "competition": "LOW",
      "text": "spring"
    },
    {
      "avg_monthly_searches": 22200,
      "competition": "HIGH",
      "text": "boot"
    },
    {
      "avg_monthly_searches": 9900,
      "competition": "LOW",
      "text": "api"
    },
    {
      "avg_monthly_searches": 1600,
      "competition": "LOW",
      "text": "iot"
    },
    {
      "avg_monthly_searches": 22200,
      "competition": "LOW",
      "text": "app"
    },
    {
      "avg_monthly_searches": 60500,
      "competition": "LOW",
      "text": "telegram"
    },
    {
      "avg_monthly_searches": 27100,
      "competition": "LOW",
      "text": "ubereats"
    }
  ],
  "recommended_url": [
    {
      "avg_monthly_searches": 8100,
      "competition": "LOW",
      "text": "software engineering"
    },
    {
      "avg_monthly_searches": 1000,
      "competition": "LOW",
      "text": "software development"
    },
    {
      "avg_monthly_searches": 30,
      "competition": "LOW",
      "text": "computer science coding"
    },
    {
      "avg_monthly_searches": 90,
      "competition": "LOW",
      "text": "computer software engineer"
    },
    {
      "avg_monthly_searches": 590,
      "competition": "MEDIUM",
      "text": "code learning"
    },
    {
      "avg_monthly_searches": 390,
      "competition": "LOW",
      "text": "code website"
    },
    {
      "avg_monthly_searches": 110,
      "competition": "LOW",
      "text": "code testing"
    },
    {
      "avg_monthly_searches": 20,
      "competition": "LOW",
      "text": "code with google"
    },
    {
      "avg_monthly_searches": 90,
      "competition": "LOW",
      "text": "app coder"
    },
    {
      "avg_monthly_searches": 20,
      "competition": "LOW",
      "text": "software engineer coding"
    },
    {
      "avg_monthly_searches": 390,
      "competition": "LOW",
      "text": "code for life"
    },
    {
      "avg_monthly_searches": 10,
      "competition": "LOW",
      "text": "coding work"
    },
    {
      "avg_monthly_searches": 10,
      "competition": "MEDIUM",
      "text": "software development education"
    },
    {
      "avg_monthly_searches": 210,
      "competition": "LOW",
      "text": "computer code"
    },
    {
      "avg_monthly_searches": 10,
      "competition": "LOW",
      "text": "tech coding"
    },
    {
      "avg_monthly_searches": 140,
      "competition": "LOW",
      "text": "software building"
    },
    {
      "avg_monthly_searches": 590,
      "competition": "LOW",
      "text": "code programs"
    },
    {
      "avg_monthly_searches": 90,
      "competition": "MEDIUM",
      "text": "help with code"
    },
    {
      "avg_monthly_searches": 20,
      "competition": "LOW",
      "text": "it software development"
    },
    {
      "avg_monthly_searches": 10,
      "competition": "LOW",
      "text": "about software engineering"
    }
  ],
  "subpages": [
    "https://keshav.codes/aakarshan",
    "https://keshav.codes/seeinghome",
    "https://keshav.codes/havmor-movies",
    "https://keshav.codes/admin-dashboard",
    "https://keshav.codes/",
    "https://keshav.codes/bigdata",
    "https://keshav.codes/bump",
    "https://keshav.codes/angular2-timeline",
    "https://keshav.codes/chainreaction",
    "https://keshav.codes/edithminibot",
    "https://keshav.codes/block-vote",
    "https://keshav.codes/payment-dbs",
    "https://keshav.codes/synopsis",
    "https://keshav.codes/iot"
  ],
  "text": "     Keshav Lingala  Software Development Engineer   Hey there, I'm Keshav! Think of me as a coding Swiss Army knife in the form of a master's student in computer science. Got a problem? I've probably got a script for that—or I'm already coding one! 🤓 From the classics like Java and Python to the cool kids on the block like AWS and Kubernetes, I've got my bases covered. I'm all about that clean code life and squeezing every last drop of performance out of my projects. So buckle up, you're in for a tech-tastic ride through my portfolio! Reach out to me anytime at  keshavlingala@gmail.com Projects   Voting Application using Blockchain Technologies BlockVote A Blockchain based Voting Application using Angular, Truffle, Solidity, Web3, Ganache, Sepolia, Material Design  -   May 2023  Real time Processing of Splitwise Data using Bigdata Technologies This is project to demonstrate the use of multiple big data technologies to process the splitwise data in real time. The project is divided into two parts. The first part is to process the data in real time and the second part is to process the data in batch mode. The project is implemented using Kafka, Spark, Spring Boot, Cassandra, Docker, Docker Compose. -   May 2023 Chain Reaction Game with AI (Minimax Algorithm) This is project to demonstrate the use of multiple big data technologies to process the splitwise data in real time. The project is divided into two parts. The first part is to process the data in real time and the second part is to process the data in batch mode. The project is implemented using Kafka, Spark, Spring Boot, Cassandra, Docker, Docker Compose. -   Dec 2022 Simple Payment Full Stack Application Developed a Simple Full stack Payment Application with Spring Boot REST API, MariaDB, Angular 11 as Front-End -   Aug 2021 Business Unit to Manage Potholes Developed a Pothole Managing System with Java Spring Boot API + Angular 11+ MySQL with client-server architecture that enables citizens to report any pothole. Deployed using AWS RDS, Heroku, Firebase -   May 2021 Smart Conference IOT Room Admin Dashboard Smart Conference IOT Room Admin Dashboard -   Mar 2021 Synopsis Chrome Extension Build a Chrome Extension that summarize any article, text, document, webpage or essay in a single click. and highlighting important lines automatically using NLP -   Feb 2021 Telegram NLP ChatBot Webhook using NodeJS A simple Telegram bot I created in Node.js to help with weather, movies or a random joke, this can also fetch audio from youtube just with a link so you can download in your device as an mp3 file When not using any of those functionalities replies with an appripriate message using NLP -   Jan 2021 Angular Library: angular2-timeline CSS based Angular Library to present any dynamic data in a timeline view with customizable colors and item design. -   Aug 2020 Social Media Platform (Aakarshan Artboard) Designed, Architected, Developed and Deployed a productivity platform for students built with Angular 9, Google Firebase, Google Material Design, Bootstrap. Architected for the purpose of sharing arts between students. Features: Dynamic Progressive Web Application , User authentication, Comments, Likes, Compressing Images client-side, offline capability Database Design in Google Firebase Firestore Fully Functional -   Jun 2019 Zonal Dashboard for Students Developed an educational platform built with Angular 7, Google Firebase, Bootstrap. Architected for the purpose of collaboration between students. Won 2nd Place on Scholar-jet way fair competition. implemented with features like status updates and knowledge with a quiz, and get to maintain combined schedules and deadlines for all the fellow users -   May 2019 Havmor Movies Web app This is a prototype of dynamic Angular app, It's  free torrent app built using open source Popcorn Times API. Movies list will get updated as soon as the YIFY database is updated. This is an inspiration from popcorn times🍿. Used OMDB API🧠 for movie info -   Apr 2019 IOT Projects IOT Projects on Raspberry Pi, Arduino and several Other Technologies ... -   Sep 2018 Work Experience    Senior Officer, Full Stack Development DBS Bank August 2021   -   August 2022 Hyderabad, India Worked on designing architecture and building software for Multi-currency Business Account Opening System. Coordinated with cross-functional teams in Singapore, Hong Kong, and China to better understand user stories and develop new functionalities. Efficiently implemented new features, Code cleanup, and optimization at the front end resulted in a 28% increase in application performance  Designed and Implemented an Angular Library for Client-Side Error Log to Server for Crash reporting & runtime errors for a holistic overview of the app's health in real-time, resulting in a 20% increase in development productivity. (Spring Boot REST Service, Angular Library, HTTP, MVC Developed and maintained CI/CD pipelines using Jenkins and Bitbucket, resulting in a 50% reduction in deployment failures Led the migration of legacy monolithic applications to microservices architecture, resulting in improved scalability and reliability Improved team efficiency by implementing standardized development and deployment processes Software Engineer Intern CoMakeIT April 2021   -   July 2021 Hyderabad, India Designed a POC to implement User Authority Management, caching, Spring MVC, and Hibernate ORM Extensively worked on a Cross-Platform App communicating with hardware devices by API calls. (Ionic Framework, JavaScript, Java, Swift) Software Development Intern Virtusa June 2020   -   Nov 2020 Bangalore, India Collaborate with design and back-end teams to develop and maintain the company's web applications Collaborated with back-end engineers to design and consume RESTful APIs for data retrieval and manipulation Implemented reusable libraries for the company's design system, resulting in a significant reduction in development time for new projects Improved accessibility compliance of the applications by implementing WCAG 2.0 standards and conducting accessibility testing Education California State University, Fullerton Master of Science in Computer Science Fullerton, California 2022   -   Present 3.94/4 CGPA Keshav Memorial Institute of Technology Computer Science and Engineering Hyderabad, India 2017   -   2021 7.61 CGPA Skills & Languages    All Skills  Server Side Technologies  Analytical and Problem solving  Web Technologies  Automation scripting  Database Technologies  IOT  Machine Learning  DevOps & Cloud Technologies                                    Get In Touch   Name Email  Message  Submit  Submitted Successfully  Designed and Developed by  Keshav Lingala   Blazing fast  with  Gatsby  and  Emotion    ",
  "top_keywords": {
    "2021": 9,
    "angular": 10,
    "api": 5,
    "app": 5,
    "application": 6,
    "boot": 5,
    "data": 11,
    "design": 7,
    "developed": 6,
    "development": 6,
    "implemented": 6,
    "iot": 5,
    "process": 6,
    "project": 6,
    "projects": 5,
    "real": 6,
    "spring": 6,
    "technologies": 9,
    "time": 7,
    "using": 12
  }
}
